---
name: CAM-PDF
version: 1.02_02
author:
  - 'Clotho Advanced Media, Inc. <cpan@clotho.com>'
abstract: PDF manipulation library
license: perl
requires:
  Crypt::RC4: 2.02
  Digest::MD5: 2.16
  Text::PDF::File: 0.18
  perl: 5.6.0
recommends:
  Getopt::Long: 2.0
  Pod::Usage: 1.0
build_requires:
  Test::More: 0
provides:
  CAM::PDF:
    file: lib/CAM/PDF.pm
    version: 1.02_02
  CAM::PDF::Content:
    file: lib/CAM/PDF/Content.pm
    version: 1.02_02
  CAM::PDF::Decrypt:
    file: lib/CAM/PDF/Decrypt.pm
    version: 1.02_02
  CAM::PDF::GS:
    file: lib/CAM/PDF/GS.pm
    version: 1.02_02
  CAM::PDF::GS::NoText:
    file: lib/CAM/PDF/GS/NoText.pm
    version: 1.02_02
  CAM::PDF::Node:
    file: lib/CAM/PDF/Node.pm
    version: 1.02_02
  CAM::PDF::PageText:
    file: lib/CAM/PDF/PageText.pm
    version: 1.02_02
  CAM::PDF::Renderer::Dump:
    file: lib/CAM/PDF/Renderer/Dump.pm
    version: 1.02_02
  CAM::PDF::Renderer::Images:
    file: lib/CAM/PDF/Renderer/Images.pm
    version: 1.02_02
  CAM::PDF::Renderer::Text:
    file: lib/CAM/PDF/Renderer/Text.pm
    version: 1.02_02
  CAM::PDF::Renderer::Text::FB:
    file: lib/CAM/PDF/Renderer/Text.pm
    version: 1.02_02
generated_by: Module::Build version 0.2611
