---
name: CAM-PDF
version: 1.13
author:
  - 'Clotho Advanced Media, Inc. <cpan@clotho.com>'
abstract: PDF manipulation library
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Crypt::RC4: 2.02
  Digest::MD5: 2.16
  Text::PDF: 0.29
  perl: 5.6.0
build_requires:
  Test::More: 0
recommends:
  Getopt::Long: 2.0
  Pod::Usage: 1.0
  Test::Memory::Cycle: 1.02
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  CAM::PDF:
    file: lib/CAM/PDF.pm
    version: 1.13
  CAM::PDF::Content:
    file: lib/CAM/PDF/Content.pm
    version: 1.13
  CAM::PDF::Decrypt:
    file: lib/CAM/PDF/Decrypt.pm
    version: 1.13
  CAM::PDF::GS:
    file: lib/CAM/PDF/GS.pm
    version: 1.13
  CAM::PDF::GS::NoText:
    file: lib/CAM/PDF/GS/NoText.pm
    version: 1.13
  CAM::PDF::Node:
    file: lib/CAM/PDF/Node.pm
    version: 1.13
  CAM::PDF::PageText:
    file: lib/CAM/PDF/PageText.pm
    version: 1.13
  CAM::PDF::Renderer::Dump:
    file: lib/CAM/PDF/Renderer/Dump.pm
    version: 1.13
  CAM::PDF::Renderer::Images:
    file: lib/CAM/PDF/Renderer/Images.pm
    version: 1.13
  CAM::PDF::Renderer::Text:
    file: lib/CAM/PDF/Renderer/Text.pm
    version: 1.13
  CAM::PDF::Renderer::TextFB:
    file: lib/CAM/PDF/Renderer/TextFB.pm
    version: 1.13
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
